version: "3.9"

services:
  frontend:
    build:
      context: .
    container_name: orenet_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
